service: itamgames

plugins:
  - serverless-offline
  - serverless-webpack

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  environment: ${file(./environments/env.${self:provider.stage}.yml):environment}
  timeout: 30
  runtime: nodejs12.x

functions:
  api:
    handler: src/server.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    cors:
      origin: '*'

